# Generated by Django 6.0.6 on 2026-07-05 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('localisation', models.CharField(max_length=255)),
                ('capacitee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('quantitee', models.IntegerField()),
                ('date_expiration', models.DateTimeField(auto_now_add=True)),
                ('etat', models.CharField(choices=[('disponible', 'Disponible'), ('reserve', 'Réservé'), ('perime', 'Perimé')], default='disponible', max_length=20)),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.warehouse')),
            ],
        ),
    ]
